[package]
name = "codequest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
crossterm = "0.27"
pulldown-cmark = "0.10.0"
termimad = "0.29.0"
